# **CALCULO DE LA MATRIZ JACOBIANA EN PYTHON**

## JUAN JOSE RESTREPO ROSERO

### ROBOTICA 2023-2

In [81]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt
#from mpl_toolkits.mplot3d import AxeStheta3D

## Definimos las variables


In [48]:

b1, b2, b3, theta1, theta2, theta3 = sym.symbols('b1 b2 b3 theta1 theta2 theta3 ')
a1, a2, a3, alpha1, alpha2, alpha3 = sym.symbols('a1 a2 a3 alpha1 alpha2 alpha3')

print(b1, b2, b3)
print(theta1, theta2, theta3)

print(a1, a2, a3)
print(alpha1, alpha2, alpha3)


b1 b2 b3
theta1 theta2 theta3
a1 a2 a3
alpha1 alpha2 alpha3


### **Definimos las matrices $ Tb_n, Ttetha_n, Ta_n$ y $Talpha_n $**

In [49]:
Ctheta1 = sym.cos(theta1)
Ctheta2 = sym.cos(theta2)
Ctheta3 = sym.cos(theta3)

Stheta1 = sym.sin(theta1)
Stheta2 = sym.sin(theta2)
Stheta3 = sym.sin(theta3)

Calpha1 = sym.cos(alpha1)
Calpha2 = sym.cos(alpha2)
Calpha3 = sym.cos(alpha3)

Salpha1 = sym.sin(alpha1)
Salpha2 = sym.sin(alpha2)
Salpha3 = sym.sin(alpha3)


print("thetas")
print(Ctheta1, Ctheta2, Ctheta3)
print(Stheta1, Stheta2, Stheta3)
print("\nalphas")
print(Calpha1, Calpha2, Calpha3)
print(Salpha1, Salpha2, Salpha3)


thetas
cos(theta1) cos(theta2) cos(theta3)
sin(theta1) sin(theta2) sin(theta3)

alphas
cos(alpha1) cos(alpha2) cos(alpha3)
sin(alpha1) sin(alpha2) sin(alpha3)


In [50]:

Tb1 = sym.Matrix([ [1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, b1],
                  [0, 0, 0, 1] ])

Tb2 = sym.Matrix([ [1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, b2],
                  [0, 0, 0, 1] ])

Tb3 = sym.Matrix([ [1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, b3],
                  [0, 0, 0, 1] ])

print("\nTb1:\n", np.matrix(Tb1) )
print("\nTb2:\n", np.matrix(Tb2) )
print("\nTb3:\n", np.matrix(Tb3) )


Tb1:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 b1]
 [0 0 0 1]]

Tb2:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 b2]
 [0 0 0 1]]

Tb3:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 b3]
 [0 0 0 1]]


In [51]:
Ttetha1 = sym.Matrix( [[Ctheta1, -Stheta1, 0, 0],
                       [Stheta1, Ctheta1, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]] )

Ttetha2 = sym.Matrix( [[Ctheta2, -Stheta2, 0, 0],
                       [Stheta2, Ctheta2, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]] )

Ttetha3 = sym.Matrix( [[Ctheta3, -Stheta3, 0, 0],
                       [Stheta3, Ctheta3, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]] )

print("\nTtetha1:\n", np.matrix(Ttetha1) )
print("\nTtetha2:\n", np.matrix(Ttetha2) )
print("\nTtetha3:\n", np.matrix(Ttetha3) )


Ttetha1:
 [[cos(theta1) -sin(theta1) 0 0]
 [sin(theta1) cos(theta1) 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Ttetha2:
 [[cos(theta2) -sin(theta2) 0 0]
 [sin(theta2) cos(theta2) 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Ttetha3:
 [[cos(theta3) -sin(theta3) 0 0]
 [sin(theta3) cos(theta3) 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [52]:
Ta1 = sym.Matrix( [[1, 0, 0, a1],
                   [0, 1, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1]] )

Ta2 = sym.Matrix( [[1, 0, 0, a2],
                   [0, 1, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1]] )

Ta3 = sym.Matrix( [[1, 0, 0, a3],
                   [0, 1, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1]] )

print("\nTa1:\n", np.matrix(Ta1) )
print("\nTa2:\n", np.matrix(Ta2) )
print("\nTa3:\n", np.matrix(Ta3) )


Ta1:
 [[1 0 0 a1]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Ta2:
 [[1 0 0 a2]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Ta3:
 [[1 0 0 a3]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [53]:
Talpha1 = sym.Matrix( [[1, 0, 0, 0],
                       [0, Calpha1, -Salpha1, 0],
                       [0, Salpha1, Calpha1, 0],
                       [0, 0, 0, 1]] )

Talpha2 = sym.Matrix( [[1, 0, 0, 0],
                       [0, Calpha2, -Salpha2, 0],
                       [0, Salpha2, Calpha2, 0],
                       [0, 0, 0, 1]] )

Talpha3 = sym.Matrix([[1, 0, 0, 0],
                      [0, Calpha3, -Salpha3, 0],
                      [0, Salpha3, Calpha3, 0],
                      [0, 0, 0, 1]] )

print("\nTalpha1:\n", np.matrix(Talpha1) )
print("\nTalpha2:\n", np.matrix(Talpha2) )
print("\nTalpha3:\n", np.matrix(Talpha3) )


Talpha1:
 [[1 0 0 0]
 [0 cos(alpha1) -sin(alpha1) 0]
 [0 sin(alpha1) cos(alpha1) 0]
 [0 0 0 1]]

Talpha2:
 [[1 0 0 0]
 [0 cos(alpha2) -sin(alpha2) 0]
 [0 sin(alpha2) cos(alpha2) 0]
 [0 0 0 1]]

Talpha3:
 [[1 0 0 0]
 [0 cos(alpha3) -sin(alpha3) 0]
 [0 sin(alpha3) cos(alpha3) 0]
 [0 0 0 1]]


### **Matriz T1**

In [54]:
T1 = Tb1 * Ttetha1 * Ta1 * Talpha1 

print("\nMatriz T1\n\n", np.matrix(T1) )


Matriz T1

 [[cos(theta1) -sin(theta1)*cos(alpha1) sin(alpha1)*sin(theta1)
  a1*cos(theta1)]
 [sin(theta1) cos(alpha1)*cos(theta1) -sin(alpha1)*cos(theta1)
  a1*sin(theta1)]
 [0 sin(alpha1) cos(alpha1) b1]
 [0 0 0 1]]


### **Matriz T2**

In [55]:
T2 = Tb2 * Ttetha2 * Ta2 * Talpha2 

print("\nMatriz T2\n\n", np.matrix(T2) )


Matriz T2

 [[cos(theta2) -sin(theta2)*cos(alpha2) sin(alpha2)*sin(theta2)
  a2*cos(theta2)]
 [sin(theta2) cos(alpha2)*cos(theta2) -sin(alpha2)*cos(theta2)
  a2*sin(theta2)]
 [0 sin(alpha2) cos(alpha2) b2]
 [0 0 0 1]]


### **Matriz T3**

In [56]:
T3 = Tb3 * Ttetha3 * Ta3 * Talpha3 

print("\nMatriz T3\n\n", np.matrix(T3) )


Matriz T3

 [[cos(theta3) -sin(theta3)*cos(alpha3) sin(alpha3)*sin(theta3)
  a3*cos(theta3)]
 [sin(theta3) cos(alpha3)*cos(theta3) -sin(alpha3)*cos(theta3)
  a3*sin(theta3)]
 [0 sin(alpha3) cos(alpha3) b3]
 [0 0 0 1]]


### Reemplazando los valores

In [83]:

valores_T1 = {alpha1:0, b1:0}
valores_T2 = {alpha2:0, b2:0}
valores_T3 = {alpha3:0, b3:0}
T1_sub = T1.subs(valores_T1)
T2_sub = T2.subs(valores_T2)
T3_sub = T3.subs(valores_T3)

#print("alpha1: ", alpha1)
print("\nMatriz T1\n\n", np.matrix(T1_sub) )
print("\nMatriz T2\n\n", np.matrix(T2_sub) )
print("\nMatriz T3\n\n", np.matrix(T3_sub) )


Matriz T1

 [[cos(theta1) -sin(theta1) 0 a1*cos(theta1)]
 [sin(theta1) cos(theta1) 0 a1*sin(theta1)]
 [0 0 1 0]
 [0 0 0 1]]

Matriz T2

 [[cos(theta2) -sin(theta2) 0 a2*cos(theta2)]
 [sin(theta2) cos(theta2) 0 a2*sin(theta2)]
 [0 0 1 0]
 [0 0 0 1]]

Matriz T3

 [[cos(theta3) -sin(theta3) 0 a3*cos(theta3)]
 [sin(theta3) cos(theta3) 0 a3*sin(theta3)]
 [0 0 1 0]
 [0 0 0 1]]


### **Obtenemos la Matriz T**

T = T1 * T2 * T3

In [58]:
T = T1_sub * T2_sub * T3_sub
print("\nMatriz T\n\n", np.matrix(T))


Matriz T

 [[(-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*cos(theta3) + (-sin(theta1)*cos(theta2) - sin(theta2)*cos(theta1))*sin(theta3)
  -(-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*sin(theta3) + (-sin(theta1)*cos(theta2) - sin(theta2)*cos(theta1))*cos(theta3)
  0
  a1*cos(theta1) - a2*sin(theta1)*sin(theta2) + a2*cos(theta1)*cos(theta2) + a3*(-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*cos(theta3) + a3*(-sin(theta1)*cos(theta2) - sin(theta2)*cos(theta1))*sin(theta3)]
 [(-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*sin(theta3) + (sin(theta1)*cos(theta2) + sin(theta2)*cos(theta1))*cos(theta3)
  (-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*cos(theta3) - (sin(theta1)*cos(theta2) + sin(theta2)*cos(theta1))*sin(theta3)
  0
  a1*sin(theta1) + a2*sin(theta1)*cos(theta2) + a2*sin(theta2)*cos(theta1) + a3*(-sin(theta1)*sin(theta2) + cos(theta1)*cos(theta2))*sin(theta3) + a3*(sin(theta1)*cos(theta2) + sin(theta2)*cos(theta1))*cos(theta3)]
 [0 0 1 0]
 [0

### Simplificamos la **Matriz T**

In [59]:
T_simplified = sym.simplify(T)
print("\nMatriz T Simplificada\n\n", np.matrix(T_simplified))


Matriz T Simplificada

 [[cos(theta1 + theta2 + theta3) -sin(theta1 + theta2 + theta3) 0
  a1*cos(theta1) + a2*cos(theta1 + theta2) + a3*cos(theta1 + theta2 + theta3)]
 [sin(theta1 + theta2 + theta3) cos(theta1 + theta2 + theta3) 0
  a1*sin(theta1) + a2*sin(theta1 + theta2) + a3*sin(theta1 + theta2 + theta3)]
 [0 0 1 0]
 [0 0 0 1]]


### Obtenemos los ***fx, fy y fz***

In [60]:
fx = T_simplified[0, 3]
print("fx: ", fx)
fy = T_simplified[1, 3]
print("fy: ", fy)
fz = T_simplified[2, 3]
print("fz: ", fz)

fx:  a1*cos(theta1) + a2*cos(theta1 + theta2) + a3*cos(theta1 + theta2 + theta3)
fy:  a1*sin(theta1) + a2*sin(theta1 + theta2) + a3*sin(theta1 + theta2 + theta3)
fz:  0


### Obtenemos la ***Matriz Jacobiana***

In [61]:
dxtheta1 = sym.diff(fx, theta1)
dxtheta2 = sym.diff(fx, theta2)
dxtheta3 = sym.diff(fx, theta3)
print("dxtheta 1: ", dxtheta1)
print("\ndxtheta 2: ", dxtheta2)
print("\ndxtheta 3: ", dxtheta3)

dytheta1 = sym.diff(fy, theta1)
dytheta2 = sym.diff(fy, theta2)
dytheta3 = sym.diff(fy, theta3)
print("\n\ndytheta 1: ", dytheta1)
print("\ndytheta 2: ", dytheta2)
print("\ndytheta 3: ", dytheta3)

dztheta1 = sym.diff(fz, theta1)
dztheta2 = sym.diff(fz, theta2)
dztheta3 = sym.diff(fz, theta3)
print("\n\ndztheta 1: ", dztheta1)
print("\ndztheta 2: ", dztheta2)
print("\ndztheta 3: ", dztheta3)


dxtheta 1:  -a1*sin(theta1) - a2*sin(theta1 + theta2) - a3*sin(theta1 + theta2 + theta3)

dxtheta 2:  -a2*sin(theta1 + theta2) - a3*sin(theta1 + theta2 + theta3)

dxtheta 3:  -a3*sin(theta1 + theta2 + theta3)


dytheta 1:  a1*cos(theta1) + a2*cos(theta1 + theta2) + a3*cos(theta1 + theta2 + theta3)

dytheta 2:  a2*cos(theta1 + theta2) + a3*cos(theta1 + theta2 + theta3)

dytheta 3:  a3*cos(theta1 + theta2 + theta3)


dztheta 1:  0

dztheta 2:  0

dztheta 3:  0


In [62]:
J = sym.Matrix([ [dxtheta1, dxtheta2, dxtheta3], 
               [dytheta1, dytheta2, dytheta3],
               [dztheta1, dztheta2, dztheta3] ])

print("\nMatriz Jacobiana\n\n", np.matrix(J))


Matriz Jacobiana

 [[-a1*sin(theta1) - a2*sin(theta1 + theta2) - a3*sin(theta1 + theta2 + theta3)
  -a2*sin(theta1 + theta2) - a3*sin(theta1 + theta2 + theta3)
  -a3*sin(theta1 + theta2 + theta3)]
 [a1*cos(theta1) + a2*cos(theta1 + theta2) + a3*cos(theta1 + theta2 + theta3)
  a2*cos(theta1 + theta2) + a3*cos(theta1 + theta2 + theta3)
  a3*cos(theta1 + theta2 + theta3)]
 [0 0 0]]


### Finalmente, obtenemos los $ \dot{x}, \dot{y}$ y $ \dot{z} $



In [82]:
x_derivada = J[0, :] #J.row(0)
y_derivada = J[1, :] #J.row(1)
z_derivada = J[2, :] #J.row(2)

print("x derivada: ", x_derivada)
print("\ny derivada: ", y_derivada)
print("\nz derivada: ", z_derivada)


x derivada:  Matrix([[-a1*sin(theta1) - a2*sin(theta1 + theta2) - a3*sin(theta1 + theta2 + theta3), -a2*sin(theta1 + theta2) - a3*sin(theta1 + theta2 + theta3), -a3*sin(theta1 + theta2 + theta3)]])

y derivada:  Matrix([[a1*cos(theta1) + a2*cos(theta1 + theta2) + a3*cos(theta1 + theta2 + theta3), a2*cos(theta1 + theta2) + a3*cos(theta1 + theta2 + theta3), a3*cos(theta1 + theta2 + theta3)]])

z derivada:  Matrix([[0, 0, 0]])


## **FIN DEL PROGRAMA**

### **Matriz T2** MALA

In [17]:
'''
T2 = sym.Matrix( [ [Ctheta2, -Stheta2, 0, a2*Ctheta2], 
                  [Stheta2, Ctheta2, 0, a2*Stheta2], 
                  [0, 0, sym.Symbol('1'), 0], 
                  [0, 0, 0, sym.Symbol('1')] ])

print("\nMatriz T2\n\n", np.matrix(T2) )

'''

'\nT2 = sym.Matrix( [ [Ctheta2, -Stheta2, 0, a2*Ctheta2], \n                  [Stheta2, Ctheta2, 0, a2*Stheta2], \n                  [0, 0, sym.Symbol(\'1\'), 0], \n                  [0, 0, 0, sym.Symbol(\'1\')] ])\n\nprint("\nMatriz T2\n\n", np.matrix(T2) )\n\n'

Matriz T3

In [18]:
T23 = T2*T3
print("\nMatriz T23\n\n", np.matrix(T23))



Matriz T23

 [[-sin(theta2)*sin(theta3)*cos(alpha2) + cos(theta2)*cos(theta3)
  sin(alpha2)*sin(alpha3)*sin(theta2) - sin(theta2)*cos(alpha2)*cos(alpha3)*cos(theta3) - sin(theta3)*cos(alpha3)*cos(theta2)
  sin(alpha2)*sin(theta2)*cos(alpha3) + sin(alpha3)*sin(theta2)*cos(alpha2)*cos(theta3) + sin(alpha3)*sin(theta3)*cos(theta2)
  a2*cos(theta2) - a3*sin(theta2)*sin(theta3)*cos(alpha2) + a3*cos(theta2)*cos(theta3) + b3*sin(alpha2)*sin(theta2)]
 [sin(theta2)*cos(theta3) + sin(theta3)*cos(alpha2)*cos(theta2)
  -sin(alpha2)*sin(alpha3)*cos(theta2) - sin(theta2)*sin(theta3)*cos(alpha3) + cos(alpha2)*cos(alpha3)*cos(theta2)*cos(theta3)
  -sin(alpha2)*cos(alpha3)*cos(theta2) + sin(alpha3)*sin(theta2)*sin(theta3) - sin(alpha3)*cos(alpha2)*cos(theta2)*cos(theta3)
  a2*sin(theta2) + a3*sin(theta2)*cos(theta3) + a3*sin(theta3)*cos(alpha2)*cos(theta2) - b3*sin(alpha2)*cos(theta2)]
 [sin(alpha2)*sin(theta3)
  sin(alpha2)*cos(alpha3)*cos(theta3) + sin(alpha3)*cos(alpha2)
  -sin(alpha2)*sin(alpha3)*

Simplificamos la matrix T12

In [19]:
T23_simplified = sym.simplify(T23)
print("\nMatriz T23 Simplificada\n\n", np.matrix(T23_simplified))
#T23_2_simplified = sym.simplify(T_23)
#print("\nMatriz T23_2 Simplificada\n\n", np.matrix(T23_2_simplified))


Matriz T23 Simplificada

 [[-sin(theta2)*sin(theta3)*cos(alpha2) + cos(theta2)*cos(theta3)
  sin(alpha2)*sin(alpha3)*sin(theta2) - sin(theta2)*cos(alpha2)*cos(alpha3)*cos(theta3) - sin(theta3)*cos(alpha3)*cos(theta2)
  sin(alpha2)*sin(theta2)*cos(alpha3) + sin(alpha3)*sin(theta2)*cos(alpha2)*cos(theta3) + sin(alpha3)*sin(theta3)*cos(theta2)
  a2*cos(theta2) - a3*sin(theta2)*sin(theta3)*cos(alpha2) + a3*cos(theta2)*cos(theta3) + b3*sin(alpha2)*sin(theta2)]
 [sin(theta2)*cos(theta3) + sin(theta3)*cos(alpha2)*cos(theta2)
  -sin(alpha2)*sin(alpha3)*cos(theta2) - sin(theta2)*sin(theta3)*cos(alpha3) + cos(alpha2)*cos(alpha3)*cos(theta2)*cos(theta3)
  -sin(alpha2)*cos(alpha3)*cos(theta2) + sin(alpha3)*sin(theta2)*sin(theta3) - sin(alpha3)*cos(alpha2)*cos(theta2)*cos(theta3)
  a2*sin(theta2) + a3*sin(theta2)*cos(theta3) + a3*sin(theta3)*cos(alpha2)*cos(theta2) - b3*sin(alpha2)*cos(theta2)]
 [sin(alpha2)*sin(theta3)
  sin(alpha2)*cos(alpha3)*cos(theta3) + sin(alpha3)*cos(alpha2)
  -sin(alpha2)

Obtemos los fx, fy, fz

In [20]:
fx = T23_simplified[0, 3]
print(fx)
fy = T23_simplified[1, 3]
print(fy)
fz = T23_simplified[2, 3]
print(fz)

a2*cos(theta2) - a3*sin(theta2)*sin(theta3)*cos(alpha2) + a3*cos(theta2)*cos(theta3) + b3*sin(alpha2)*sin(theta2)
a2*sin(theta2) + a3*sin(theta2)*cos(theta3) + a3*sin(theta3)*cos(alpha2)*cos(theta2) - b3*sin(alpha2)*cos(theta2)
a3*sin(alpha2)*sin(theta3) + b2 + b3*cos(alpha2)


Obtenemos la Matriz Jacobiana

In [21]:
dxtheta2 = sym.diff(fx, theta2)
dxtheta3 = sym.diff(fx, theta3)

dytheta2 = sym.diff(fy, theta2)
dytheta3 = sym.diff(fy, theta3)

dztheta2 = sym.diff(fz, theta2)
dztheta3 = sym.diff(fz, theta3)

J = sym.Matrix([ [dxtheta2, dxtheta3], 
               [dytheta2, dytheta3],
               [dztheta2, dztheta3] ])

print("\nMatriz Jacobiana\n\n", np.matrix(J))


Matriz Jacobiana

 [[-a2*sin(theta2) - a3*sin(theta2)*cos(theta3) - a3*sin(theta3)*cos(alpha2)*cos(theta2) + b3*sin(alpha2)*cos(theta2)
  -a3*sin(theta2)*cos(alpha2)*cos(theta3) - a3*sin(theta3)*cos(theta2)]
 [a2*cos(theta2) - a3*sin(theta2)*sin(theta3)*cos(alpha2) + a3*cos(theta2)*cos(theta3) + b3*sin(alpha2)*sin(theta2)
  -a3*sin(theta2)*sin(theta3) + a3*cos(alpha2)*cos(theta2)*cos(theta3)]
 [0 a3*sin(alpha2)*cos(theta3)]]


Ahora sustituiremos las variables por valores numericos

In [22]:
Tb2_sub = Tb2.subs(b2, 300)
Tb3_sub = Tb3.subs(b3, 0)


print("\nVALORES SUSTITUIDOS\n")
print("Tb2_sub:\n", np.matrix(Tb2_sub) )
print("Tb3_sub:\n", np.matrix(Tb3_sub) )


VALORES SUSTITUIDOS

Tb2_sub:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 300]
 [0 0 0 1]]
Tb3_sub:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [23]:
print("\nTtetha2:\n", np.matrix(Ttetha2) )
print("\nTtetha3:\n", np.matrix(Ttetha3) )


Ttetha2:
 [[cos(theta2) -sin(theta2) 0 0]
 [sin(theta2) cos(theta2) 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Ttetha3:
 [[cos(theta3) -sin(theta3) 0 0]
 [sin(theta3) cos(theta3) 0 0]
 [0 0 1 0]
 [0 0 0 1]]
