# **CALCULO DE LA MATRIZ JACOBIANA EN PYTHON**

## JUAN JOSE RESTREPO ROSERO

### ROBOTICA 2023-2

In [ ]:
import numpy as np
import math
import sympy as sym
import matplotlib.pyplot as plt
from sympy.core.evalf import evalf
#from mpl_toolkits.mplot3d import AxeStheta3D

## Definimos las variables


In [ ]:

b1, b2, b3, theta1, theta2, theta3 = sym.symbols('b1 b2 b3 theta1 theta2 theta3 ')
a1, a2, a3, alpha1, alpha2, alpha3 = sym.symbols('a1 a2 a3 alpha1 alpha2 alpha3')

print(b1, b2, b3)
print(theta1, theta2, theta3)

print(a1, a2, a3)
print(alpha1, alpha2, alpha3)


b1 b2 b3
theta1 theta2 theta3
a1 a2 a3
alpha1 alpha2 alpha3


### **Definimos las matrices $ Tb_n, Ttetha_n, Ta_n$ y $Talpha_n $**

In [ ]:

Ctheta1 = sym.cos(theta1)
Ctheta2 = sym.cos(theta2)
Ctheta3 = sym.cos(theta3)

Stheta1 = sym.sin(theta1)
Stheta2 = sym.sin(theta2)
Stheta3 = sym.sin(theta3)

Calpha1 = sym.cos(alpha1)
Calpha2 = sym.cos(alpha2)
Calpha3 = sym.cos(alpha3)

Salpha1 = sym.sin(alpha1)
Salpha2 = sym.sin(alpha2)
Salpha3 = sym.sin(alpha3)


print("THETAS")
print(Ctheta1, Ctheta2, Ctheta3)
print(Stheta1, Stheta2, Stheta3)
print("\nALPHAS")
print(Calpha1, Calpha2, Calpha3)
print(Salpha1, Salpha2, Salpha3)


THETAS
cos(theta1) cos(theta2) cos(theta3)
sin(theta1) sin(theta2) sin(theta3)

ALPHAS
cos(alpha1) cos(alpha2) cos(alpha3)
sin(alpha1) sin(alpha2) sin(alpha3)


In [ ]:

Tb1 = sym.Matrix([ [1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, b1],
                  [0, 0, 0, 1] ])

Tb2 = sym.Matrix([ [1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, b2],
                  [0, 0, 0, 1] ])

Tb3 = sym.Matrix([ [1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 1, b3],
                  [0, 0, 0, 1] ])

print("\nTb1:\n", np.matrix(Tb1) )
print("\nTb2:\n", np.matrix(Tb2) )
print("\nTb3:\n", np.matrix(Tb3) )


Tb1:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 b1]
 [0 0 0 1]]

Tb2:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 b2]
 [0 0 0 1]]

Tb3:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 b3]
 [0 0 0 1]]


In [ ]:
Ttetha1 = sym.Matrix( [[Ctheta1, -Stheta1, 0, 0],
                       [Stheta1, Ctheta1, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]] )

Ttetha2 = sym.Matrix( [[Ctheta2, -Stheta2, 0, 0],
                       [Stheta2, Ctheta2, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]] )

Ttetha3 = sym.Matrix( [[Ctheta3, -Stheta3, 0, 0],
                       [Stheta3, Ctheta3, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]] )

print("\nTtetha1:\n", np.matrix(Ttetha1) )
print("\nTtetha2:\n", np.matrix(Ttetha2) )
print("\nTtetha3:\n", np.matrix(Ttetha3) )


Ttetha1:
 [[cos(theta1) -sin(theta1) 0 0]
 [sin(theta1) cos(theta1) 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Ttetha2:
 [[cos(theta2) -sin(theta2) 0 0]
 [sin(theta2) cos(theta2) 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Ttetha3:
 [[cos(theta3) -sin(theta3) 0 0]
 [sin(theta3) cos(theta3) 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
Ta1 = sym.Matrix( [[1, 0, 0, a1],
                   [0, 1, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1]] )

Ta2 = sym.Matrix( [[1, 0, 0, a2],
                   [0, 1, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1]] )

Ta3 = sym.Matrix( [[1, 0, 0, a3],
                   [0, 1, 0, 0],
                   [0, 0, 1, 0],
                   [0, 0, 0, 1]] )

print("\nTa1:\n", np.matrix(Ta1) )
print("\nTa2:\n", np.matrix(Ta2) )
print("\nTa3:\n", np.matrix(Ta3) )


Ta1:
 [[1 0 0 a1]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Ta2:
 [[1 0 0 a2]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Ta3:
 [[1 0 0 a3]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
Talpha1 = sym.Matrix( [[1, 0, 0, 0],
                       [0, Calpha1, -Salpha1, 0],
                       [0, Salpha1, Calpha1, 0],
                       [0, 0, 0, 1]] )

Talpha2 = sym.Matrix( [[1, 0, 0, 0],
                       [0, Calpha2, -Salpha2, 0],
                       [0, Salpha2, Calpha2, 0],
                       [0, 0, 0, 1]] )

Talpha3 = sym.Matrix([[1, 0, 0, 0],
                      [0, Calpha3, -Salpha3, 0],
                      [0, Salpha3, Calpha3, 0],
                      [0, 0, 0, 1]] )

print("\nTalpha1:\n", np.matrix(Talpha1) )
print("\nTalpha2:\n", np.matrix(Talpha2) )
print("\nTalpha3:\n", np.matrix(Talpha3) )


Talpha1:
 [[1 0 0 0]
 [0 cos(alpha1) -sin(alpha1) 0]
 [0 sin(alpha1) cos(alpha1) 0]
 [0 0 0 1]]

Talpha2:
 [[1 0 0 0]
 [0 cos(alpha2) -sin(alpha2) 0]
 [0 sin(alpha2) cos(alpha2) 0]
 [0 0 0 1]]

Talpha3:
 [[1 0 0 0]
 [0 cos(alpha3) -sin(alpha3) 0]
 [0 sin(alpha3) cos(alpha3) 0]
 [0 0 0 1]]


### **Matriz T1**

In [ ]:
T1 = Tb1 * Ttetha1 * Ta1 * Talpha1 

print("\nMatriz T1\n\n", np.matrix(T1) )


Matriz T1

 [[cos(theta1) -sin(theta1)*cos(alpha1) sin(alpha1)*sin(theta1)
  a1*cos(theta1)]
 [sin(theta1) cos(alpha1)*cos(theta1) -sin(alpha1)*cos(theta1)
  a1*sin(theta1)]
 [0 sin(alpha1) cos(alpha1) b1]
 [0 0 0 1]]


### **Matriz T2**

In [ ]:
T2 = Tb2 * Ttetha2 * Ta2 * Talpha2 

print("\nMatriz T2\n\n", np.matrix(T2) )


Matriz T2

 [[cos(theta2) -sin(theta2)*cos(alpha2) sin(alpha2)*sin(theta2)
  a2*cos(theta2)]
 [sin(theta2) cos(alpha2)*cos(theta2) -sin(alpha2)*cos(theta2)
  a2*sin(theta2)]
 [0 sin(alpha2) cos(alpha2) b2]
 [0 0 0 1]]


### **Matriz T3**

In [ ]:
T3 = Tb3 * Ttetha3 * Ta3 * Talpha3 

print("\nMatriz T3\n\n", np.matrix(T3) )


Matriz T3

 [[cos(theta3) -sin(theta3)*cos(alpha3) sin(alpha3)*sin(theta3)
  a3*cos(theta3)]
 [sin(theta3) cos(alpha3)*cos(theta3) -sin(alpha3)*cos(theta3)
  a3*sin(theta3)]
 [0 sin(alpha3) cos(alpha3) b3]
 [0 0 0 1]]


## Reemplazando los valores en las matrices **T1, T2 y T3**


CLASE
THETA1 = SYMBOLIC,
THETA2 = 90,
THETA3 = 0


ALPHA1 = 90,
ALPHA2 = 0,
ALPHA3 = 0

b1 = 300,
b2 = 0,
b3 = 0

a1 = 0,
a2 = 250,
a3 = 232

In [ ]:
'''
print(type(a1))
print(type(a2))
print(type(a3))
print(type(b1))
print(type(b2))
print(type(b3))
print(type(alpha1))
print(type(alpha2))
print(type(alpha3))
print(type(theta1))
print(type(theta2))
print(type(theta3))
'''

valores = {a1: 0, a2: 250, a3: 232, b1: 300, b2: 0, b3: 0, alpha1: sym.pi/2, alpha2: 0, alpha3: 0}



### Matriz T1 con valores sustituidos

In [ ]:
T1 = Tb1 * Ttetha1 * Ta1 * Talpha1

T1_sub = T1.subs(valores)
print(np.matrix(T1_sub))

[[cos(theta1) 0 sin(theta1) 0]
 [sin(theta1) 0 -cos(theta1) 0]
 [0 1 0 300]
 [0 0 0 1]]


### Matriz T2 con valores sustituidos

In [ ]:
T2 = Tb2 * Ttetha2 * Ta2 * Talpha2

T2_sub = T2.subs(valores)
print(np.matrix(T2_sub))

[[cos(theta2) -sin(theta2) 0 250*cos(theta2)]
 [sin(theta2) cos(theta2) 0 250*sin(theta2)]
 [0 0 1 0]
 [0 0 0 1]]


### Matriz T3 con valores sustituidos

In [ ]:
T3 = Tb3 * Ttetha3 * Ta3 * Talpha3

T3_sub = T3.subs(valores)
print(np.matrix(T3_sub))

[[cos(theta3) -sin(theta3) 0 232*cos(theta3)]
 [sin(theta3) cos(theta3) 0 232*sin(theta3)]
 [0 0 1 0]
 [0 0 0 1]]


### Simplificamos las matrices **T1, T2 y T3**

In [ ]:
T1_simplified = sym.simplify(T1_sub)
T2_simplified = sym.simplify(T2_sub)
T3_simplified = sym.simplify(T3_sub)

print("\nMatriz T1 Simplificada\n\n", np.matrix(T1_simplified))
print("\nMatriz T2 Simplificada\n\n", np.matrix(T2_simplified))
print("\nMatriz T3 Simplificada\n\n", np.matrix(T3_simplified))


Matriz T1 Simplificada

 [[cos(theta1) 0 sin(theta1) 0]
 [sin(theta1) 0 -cos(theta1) 0]
 [0 1 0 300]
 [0 0 0 1]]

Matriz T2 Simplificada

 [[cos(theta2) -sin(theta2) 0 250*cos(theta2)]
 [sin(theta2) cos(theta2) 0 250*sin(theta2)]
 [0 0 1 0]
 [0 0 0 1]]

Matriz T3 Simplificada

 [[cos(theta3) -sin(theta3) 0 232*cos(theta3)]
 [sin(theta3) cos(theta3) 0 232*sin(theta3)]
 [0 0 1 0]
 [0 0 0 1]]


### **Obtenemos la Matriz T**

T = T1 * T2 * T3


Reemplazamos los thetas

theta1 = symbolic
theta2 = 90
theta3 = 0

alpha1 = 90

In [ ]:
Tfinal = T1_simplified * T2_simplified * T3_simplified
#print("\nMatriz Tfinal\n\n", np.matrix(Tfinal))


valores = {a1: 0, a2: 250, a3: 232, b1: 300, b2: 0, b3: 0, alpha1: sym.pi/2, alpha2: 0, alpha3: 0}

Tfinal_sub = Tfinal.subs(valores)


TFinalSimplified = sym.simplify(Tfinal_sub)
print("\nMatriz Tfinal Simplificada\n\n", np.matrix(TFinalSimplified))


Matriz Tfinal Simplificada

 [[cos(theta1)*cos(theta2 + theta3) -sin(theta2 + theta3)*cos(theta1)
  sin(theta1) 2*(125*cos(theta2) + 116*cos(theta2 + theta3))*cos(theta1)]
 [sin(theta1)*cos(theta2 + theta3) -sin(theta1)*sin(theta2 + theta3)
  -cos(theta1) 2*(125*cos(theta2) + 116*cos(theta2 + theta3))*sin(theta1)]
 [sin(theta2 + theta3) cos(theta2 + theta3) 0
  250*sin(theta2) + 232*sin(theta2 + theta3) + 300]
 [0 0 0 1]]


### Obtenemos los ***fx, fy y fz***

In [ ]:
fx = TFinalSimplified[0, 3]
print("fx: ", fx)
fy = TFinalSimplified[1, 3]
print("fy: ", fy)
fz = TFinalSimplified[2, 3]
print("fz: ", fz)

fx:  2*(125*cos(theta2) + 116*cos(theta2 + theta3))*cos(theta1)
fy:  2*(125*cos(theta2) + 116*cos(theta2 + theta3))*sin(theta1)
fz:  250*sin(theta2) + 232*sin(theta2 + theta3) + 300


### Obtenemos la ***Matriz Jacobiana***

In [ ]:
dxtheta1 = sym.diff(fx, theta1)
dxtheta2 = sym.diff(fx, theta2)
dxtheta3 = sym.diff(fx, theta3)
print("dxtheta 1: ", dxtheta1)
print("\ndxtheta 2: ", dxtheta2)
print("\ndxtheta 3: ", dxtheta3)

dytheta1 = sym.diff(fy, theta1)
dytheta2 = sym.diff(fy, theta2)
dytheta3 = sym.diff(fy, theta3)
print("\n\ndytheta 1: ", dytheta1)
print("\ndytheta 2: ", dytheta2)
print("\ndytheta 3: ", dytheta3)

dztheta1 = sym.diff(fz, theta1)
dztheta2 = sym.diff(fz, theta2)
dztheta3 = sym.diff(fz, theta3)
print("\n\ndztheta 1: ", dztheta1)
print("\ndztheta 2: ", dztheta2)
print("\ndztheta 3: ", dztheta3)


dxtheta 1:  -2*(125*cos(theta2) + 116*cos(theta2 + theta3))*sin(theta1)

dxtheta 2:  2*(-125*sin(theta2) - 116*sin(theta2 + theta3))*cos(theta1)

dxtheta 3:  -232*sin(theta2 + theta3)*cos(theta1)


dytheta 1:  2*(125*cos(theta2) + 116*cos(theta2 + theta3))*cos(theta1)

dytheta 2:  2*(-125*sin(theta2) - 116*sin(theta2 + theta3))*sin(theta1)

dytheta 3:  -232*sin(theta1)*sin(theta2 + theta3)


dztheta 1:  0

dztheta 2:  250*cos(theta2) + 232*cos(theta2 + theta3)

dztheta 3:  232*cos(theta2 + theta3)


In [ ]:
Jac = sym.Matrix([ [dxtheta1, dxtheta2, dxtheta3], 
               [dytheta1, dytheta2, dytheta3],
               [dztheta1, dztheta2, dztheta3] ])

print("\nMatriz Jacobiana\n\n", np.matrix(Jac) )


Matriz Jacobiana

 [[-2*(125*cos(theta2) + 116*cos(theta2 + theta3))*sin(theta1)
  2*(-125*sin(theta2) - 116*sin(theta2 + theta3))*cos(theta1)
  -232*sin(theta2 + theta3)*cos(theta1)]
 [2*(125*cos(theta2) + 116*cos(theta2 + theta3))*cos(theta1)
  2*(-125*sin(theta2) - 116*sin(theta2 + theta3))*sin(theta1)
  -232*sin(theta1)*sin(theta2 + theta3)]
 [0 250*cos(theta2) + 232*cos(theta2 + theta3) 232*cos(theta2 + theta3)]]


In [ ]:
JacobianaSimplificada = sym.simplify(Jac)
print("\nMatriz Jacobiana Simplificada\n\n", np.matrix(JacobianaSimplificada) )


Matriz Jacobiana Simplificada

 [[-2*(125*cos(theta2) + 116*cos(theta2 + theta3))*sin(theta1)
  -2*(125*sin(theta2) + 116*sin(theta2 + theta3))*cos(theta1)
  -232*sin(theta2 + theta3)*cos(theta1)]
 [2*(125*cos(theta2) + 116*cos(theta2 + theta3))*cos(theta1)
  -2*(125*sin(theta2) + 116*sin(theta2 + theta3))*sin(theta1)
  -232*sin(theta1)*sin(theta2 + theta3)]
 [0 250*cos(theta2) + 232*cos(theta2 + theta3) 232*cos(theta2 + theta3)]]


### Reemplazando valores en la **Matriz Jacobiana Final**

In [ ]:
valores = {a1: 0, a2: 250, a3: 232, b1: 300, b2: 0, b3: 0, theta1: 0, theta3: 0, alpha1: sym.pi/2, alpha2: 0, alpha3: 0}

JacobianaSimplificada = Tfinal.subs(valores)

print("\nMatriz Tfinal Simplificada\n\n", np.matrix(JacobianaSimplificada))
print("\nMatriz Tfinal Simplificada\n\n", sym.simplify(np.matrix(JacobianaSimplificada)) )


Matriz Tfinal Simplificada

 [[cos(theta2) -sin(theta2) 0 482*cos(theta2)]
 [0 0 -1 0]
 [sin(theta2) cos(theta2) 0 482*sin(theta2) + 300]
 [0 0 0 1]]

Matriz Tfinal Simplificada

 [[cos(theta2), -sin(theta2), 0, 482*cos(theta2)], [0, 0, -1, 0], [sin(theta2), cos(theta2), 0, 482*sin(theta2) + 300], [0, 0, 0, 1]]


### Finalmente, obtenemos los $ \dot{x}, \dot{y}$ y $ \dot{z} $



In [ ]:
x_derivada = JacobianaSimplificada[0, :] #J.row(0)
y_derivada = JacobianaSimplificada[1, :] #J.row(1)
z_derivada = JacobianaSimplificada[2, :] #J.row(2)

print("x derivada: ", x_derivada)
print("\ny derivada: ", y_derivada)
print("\nz derivada: ", z_derivada)


x derivada:  Matrix([[cos(theta2), -sin(theta2), 0, 482*cos(theta2)]])

y derivada:  Matrix([[0, 0, -1, 0]])

z derivada:  Matrix([[sin(theta2), cos(theta2), 0, 482*sin(theta2) + 300]])


## **FIN DEL PROGRAMA**