In [36]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

Parametros D.H.

In [37]:
a1 = 200
tethaR1 = 45
b1 = 0
alphaR1 = 0

a2 = 150
tethaR2 = -45
b2 = 0
alphaR2 = 0

a3 = 50
tethaR3 = -90
b3 = 0
alphaR3 = 0

Conversion Radianes a Grados

In [38]:
tetha1 = (tethaR1*np.pi)/180
alpha1 = (alphaR1*np.pi)/180

tetha2 = (tethaR2*np.pi)/180
alpha2 = (alphaR2*np.pi)/180

tetha3 = (tethaR3*np.pi)/180
alpha3 = (alphaR3*np.pi)/180

Matrices de Transformacion Homegenea

In [39]:
# Parametros b ( desplazamiento en el eje Z )

Tb1 = [[1, 0, 0, 0],
      [0, 1, 0, 0],
      [0, 0, 1, b1],
      [0, 0, 0, 1]]

Tb2 = [[1, 0, 0, 0],
      [0, 1, 0, 0],
      [0, 0, 1, b2],
      [0, 0, 0, 1]]

Tb3 = [[1, 0, 0, 0],
      [0, 1, 0, 0],
      [0, 0, 1, b3],
      [0, 0, 0, 1]]

In [40]:
# Parametros Tetha ( Rotacion en el eje Z )

Ttetha1 = [[np.cos(tetha1), -np.sin(tetha1), 0, 0],
          [np.sin(tetha1), np.cos(tetha1), 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]]

Ttetha2 = [[np.cos(tetha2), -np.sin(tetha2), 0, 0],
          [np.sin(tetha2), np.cos(tetha2), 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]]
Ttetha3 = [[np.cos(tetha3), -np.sin(tetha3), 0, 0],
          [np.sin(tetha3), np.cos(tetha3), 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]]

In [41]:
# Parametros a ( desplazamiento del eslabon en el eje X  )

Ta1 = [[1, 0, 0, a1],
      [0, 1, 0, 0],
      [0, 0, 1, 0],
      [0, 0, 0, 1]]

Ta2 = [[1, 0, 0, a2],
      [0, 1, 0, 0],
      [0, 0, 1, 0],
      [0, 0, 0, 1]]

Ta3 = [[1, 0, 0, a3],
      [0, 1, 0, 0],
      [0, 0, 1, 0],
      [0, 0, 0, 1]]

In [42]:
Talpha1 = [[1, 0, 0, 0],
         [0, np.cos(alpha1), -np.sin(alpha1), 0],
          [0, np.sin(alpha1), np.cos(alpha1), 0],
          [0, 0, 0, 1]]

Talpha2 = [[1, 0, 0, 0],
         [0, np.cos(alpha2), -np.sin(alpha2), 0],
          [0, np.sin(alpha2), np.cos(alpha2), 0],
          [0, 0, 0, 1]]

Talpha3 = [[1, 0, 0, 0],
         [0, np.cos(alpha3), -np.sin(alpha3), 0],
          [0, np.sin(alpha3), np.cos(alpha3), 0],
          [0, 0, 0, 1]]

T1->0 = TL1 * TL0

TL1 = T_tras_b1 * T_rota_tetha1 * T_tras_a1 * T_rota_alpha1

TL0 = T_tras_b2 * T_rota_tetha2 * T_tras_a2 * T_rota_alpha2

In [43]:
#T1_1 = np.dot(Tb1, Ttetha1)
#T1_2 = np.dot(T1_1, Ta1)
#T1_a_0 = np.dot(T1_2, Talpha1)

T1_a_0 = np.dot(np.dot(np.dot(Tb1, Ttetha1), Ta1), Talpha1)

print("\nMatriz de Transformacion T1 -> 0 (TL1): (a1 = {} mm, b1 = {}, tetha1 = {}°, alpha1 = {}°)\n\n" .format(a1, b1, tethaR1, alphaR1), np.matrix(T1_a_0).round(3) )


Matriz de Transformacion T1 -> 0 (TL1): (a1 = 200 mm, b1 = 0, tetha1 = 45°, alpha1 = 0°)

 [[  0.707  -0.707   0.    141.421]
 [  0.707   0.707   0.    141.421]
 [  0.      0.      1.      0.   ]
 [  0.      0.      0.      1.   ]]


T2->1

In [44]:
#T2_1 = np.dot(Tb2, Ttetha2)
#T2_2 = np.dot(T2_1, Ta2)

T2_a_1 = np.dot(np.dot(np.dot(Tb2, Ttetha2), Ta2), Talpha2)

print("\nMatriz de Transformacion T2 -> 1 (TL2): (a2 = {} mm, b2 = {}, tetha2 = {}°, alpha2 = {}°)\n".format(a2, b2, tethaR2, alphaR2), np.matrix(T2_a_1).round(3) )


Matriz de Transformacion T2 -> 1 (TL2): (a2 = 150 mm, b2 = 0, tetha2 = -45°, alpha2 = 0°)
 [[   0.707    0.707    0.     106.066]
 [  -0.707    0.707    0.    -106.066]
 [   0.       0.       1.       0.   ]
 [   0.       0.       0.       1.   ]]


T3->2

In [45]:
#T3_1 = np.dot(Tb3, Ttetha3)
#T3_2 = np.dot(T3_1, Ta3)

T3_a_2 = np.dot(np.dot(np.dot(Tb3, Ttetha3), Ta3), Talpha3)

print("\nMatriz de Transformacion T3 -> 2 (TL3): (a3 = {} mm, b3 = {}, tetha3 = {}°, alpha3 = {}°)\n\n".format(a3, b3, tethaR3, alphaR3), np.matrix(T3_a_2).round(3)  )


Matriz de Transformacion T3 -> 2 (TL3): (a3 = 50 mm, b3 = 0, tetha3 = -90°, alpha3 = 0°)

 [[  0.   1.   0.   0.]
 [ -1.   0.   0. -50.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]


In [46]:
T10_21 = np.dot(T1_a_0, T2_a_1)
Tfinal = np.dot(np.dot(T1_a_0, T2_a_1), T3_a_2) 

print("\nMatriz de Transformacion TF (0 -> 3):\n\n", np.matrix(Tfinal).round(3) )


Matriz de Transformacion TF (0 -> 3):

 [[  0.      1.      0.    291.421]
 [ -1.      0.      0.     91.421]
 [  0.      0.      1.      0.   ]
 [  0.      0.      0.      1.   ]]


Obtenemos los puntos P3, P2 y P1

In [49]:
P3 = Tfinal[:3, 3]
P2 = np.array([ 291.42, 141.42, 0. ])

# Define the matrix equation
A = T3_a_2[:3, :3]
b = P3
x = np.linalg.solve(A, P2 - T3_a_2[:3, 3])

# Construct the transformation matrix
TL3 = np.identity(4)
TL3[:3, :3] = A
TL3[:3, 3] = x


In [48]:
#Volviendo P3 1x3 a una matriz 3x1
NewP3 = P3.reshape((4, 1))
NewP3_2 = np.array(NewP3)
print("\nNew P3: ", NewP3)

P2 = np.dot(T3_a_2, P3)
print("\nP2: ", P2)

ValueError: cannot reshape array of size 3 into shape (4,1)